


CREATE TABLE BOX
(
    boxid INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    width  DOUBLE DEFAULT 0,
    heigh DOUBLE DEFAULT 0
    
);


CREATE TABLE PRODUCT
(
    prodid INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    description VARCHAR(255) DEFAULT '',
    price DOUBLE DEFAULT 0,
    stock INTEGER DEFAULT 0,
    width  DOUBLE DEFAULT 0,
    heigh DOUBLE DEFAULT 0
    
);


CREATE TABLE SUMMARYCHECKOUT
(
    idcheckoutsummary INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    total DOUBLE DEFAULT 0

    
);



CREATE TABLE CHECKOUT
(
    idcheckout INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    idcheckoutsummary INTEGER ,
    boxid INTEGER ,
    prodid INTEGER ,
    CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (prodid) REFERENCES PRODUCT(prodid),
    CONSTRAINT FK_CHECKOUT_SUMMARY_ID FOREIGN KEY (idcheckoutsummary) REFERENCES SUMMARYCHECKOUT(idcheckoutsummary),
    CONSTRAINT FK_BOX_ID FOREIGN KEY (boxid) REFERENCES BOX(boxid)
);



